spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
#  kafka:
#    bootstrap-servers: 192.168.31.54:9092 # 指定kafka 代理地址，可以多个
#    consumer:
#      group-id: default-group # 指定默认消费者group id
#    template:
#      default-topic: test
#    listener:
#      concurrency: 3 # 指定listener 容器中的线程数，用于提高并发量
#    producer:
#      batch-size: 1000 # 每次批量发送消息的数量
  redis:
    host: localhost #192.168.31.54 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 192.168.31.54:9300 # 集成ES

#eureka:
#  client:
#    service-url:
#      defaultZone: http://175.24.103.79:8001/eureka/
#    registry-fetch-interval-seconds: 10
#  instance:
#    prefer-ip-address: true

# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    cn.ztuo.tea.mapper: debug
    cn.ztuo.tea.dao: debug