spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    druid:
      initial-size: 50 #连接池初始化大小
      min-idle: 20 #最小空闲连接数
      max-active: 1000 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
#  kafka:
#    bootstrap-servers: kafka:9092 # 指定kafka 代理地址，可以多个
#    consumer:
#      group-id: default-group # 指定默认消费者group id
#      enable-auto-commit: false
#      auto-commit-interval: 100
#      auto-offset-reset: earliest
#      max-poll-records: 50
#    template:
#      default-topic: prod
#    listener:
#      concurrency: 3 # 指定listener 容器中的线程数，用于提高并发量
#    producer:
#      batch-size: 1000 # 每次批量发送消息的数量
#      retries: 0
#      buffer-memory: 1048576
#  data:
#    mongodb:
#      host: mongo
#      port: 27017
#      database: wallet-portal
#      username: root
#      password: root
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000ms # 连接超时时间（毫秒）

#eureka:
#  client:
#    service-url:
#      defaultZone: http://wallet-registry:8001/eureka/
#    registry-fetch-interval-seconds: 10
#  instance:
#    prefer-ip-address: true

# 日志配置
logging:
  path: /var/logs
  level:
    cn.test.tea.mapper: debug
    cn.test.tea.dao: debug

